---
- ansible.builtin.include_tasks: "setup-{{ ansible_os_family | lower }}.yml"


- name: "include debian apt"
  ansible.builtin.include_tasks: "install-apt.yml"
  when: ansible_os_family | lower == "debian"

- name: "include debian vars"
  ansible.builtin.include_vars: "debian.yml"
  when: ansible_os_family | lower == "debian"


- name: "include install github"
  ansible.builtin.include_tasks: "install-github.yml"
  when: ansible_os_family | lower != "debian"
